spring:
  datasource:       
    url: jdbc:mysql://DB_URL/budget_app
    username: DB_USERNAME
    password: DB_PASSWORD
  jpa:
    hibernate:
      use-new-id-generator-mappings: false  
  flyway:
    locations:
    - classpath:/db/migrations  
