spring:
  datasource:       
    url: jdbc:mysql://192.168.99.100:3306/budget_app
    username: root
    password: my-secret-pw
  jpa:
    hibernate:
      use-new-id-generator-mappings: false  
  flyway:
    locations:
    - classpath:/db/migrations  