spring:
  datasource:
    url: jdbc:mysql://${db_url}/${db_name}?useSSL=false
    username: ${db_user}
    password: ${db_password}     
  jpa:
    hibernate:
      use-new-id-generator-mappings: false  
  flyway:
    baselineOnMigrate: true
    locations:
    - classpath:/db/migrations  
  cloud:
    kubernetes:
      config:
        enableApi: true
